### ISSUE TITLE
Installation instructions do not work on iMAC running Mojave 10.14.3

### ISSUE THREAD

**Issue by rduerr** [INCATools/dosdp-tools#115]
Brew was already installed:

Ruths-iMac:ResourceRegistry ruthduerr$ brew install sbt
Warning: sbt 1.2.8 is already installed and up-to-date
To reinstall 1.2.8, run `brew reinstall sbt`

but the next instruction does not work

Ruths-iMac:ResourceRegistry ruthduerr$ sbt stage
[warn] No sbt.version set in project/build.properties, base directory: /Users/ruthduerr/src/ResourceRegistry
[info] Set current project to resourceregistry (in build file:/Users/ruthduerr/src/ResourceRegistry/)
[error] Not a valid command: stage (similar: last-grep, set, last)
[error] Not a valid project ID: stage
[error] Expected ':'
[error] Not a valid key: stage (similar: state, target, tags)
[error] stage
[error]      ^
Ruths-iMac:ResourceRegistry ruthduerr$

**Comment by balhoff** [comment]
My guess from the error is that you might not be in the project directory (the root of the project where `build.sbt` is located). Could that be true?

**Comment by rduerr** [comment]
Only if you have to change directories after doing the brew install….  Yes? No?

**Comment by rduerr** [comment]
OK, so yes, you do have to change directories to where ever the build.properties file ends up, so the instructions need to be updated accordingly.

**Comment by balhoff** [comment]
Is this a little more clear? https://github.com/INCATools/dosdp-tools/commit/27f90ecf0055786d9a253094c9db9165f9ceee37

Thank you!

**Comment by rduerr** [comment]
Yes it is clearer; but I think it would be clearer still if it read as:

1. If you don't already have it, install sbt on your system. For Mac OS X, this is easily done using Homebrew <http://brew.sh/>: brew install sbt

2. Clone the project from GitHub (git clone git@github.com:INCATools/dosdp-tools.git) 

3. Change into the project directory: cd dosdp-tools. 

4. To compile and build the executable package, run: sbt stage

You will find executables for Unix and Windows in target/universal/stage/bin/. These depend on the libraries in target/universal/stage/lib.

**Comment by balhoff** [comment]
Thank you, I will paste in your text, unless you prefer to make a pull request.

**Comment by rduerr** [comment]
Oh sorry, I could have done that; but was busy and didn’t get this until now.  You can go ahead and paste it in if you’d like….

Ruth
