### ISSUE TITLE
Feature request: Make dosdp query take a list of patterns as input

### ISSUE THREAD

**Issue by matentzn** [INCATools/dosdp-tools#120]
Reloading the ontology 100 times to match all uPheno patterns uses too much electricity and takes 1 night :)

**Comment by matentzn** [comment]
the batch mode is awesome:  Tiny remarks:

- batchmode variables should be trimmed (twice)
   - --batch-patterns=" pat" breaks (space around vars)
   - --batch-patterns="pat  patx" breaks (double space between vars)
- I would like a progress thing in batchmode that says which pattern it is working on. If I deal with 100ds of patterns (which I do) it looks sad otherwise.

THIS IS AMAZING!

**Comment by balhoff** [comment]
@matentzn I can't replicate your problems with spaces. With this input:
 
```
--batch-patterns="hello  there     john  "
```

 I get `hello`, `there`, and `john`.

**Comment by matentzn** [comment]
Hmmmm.. thats strange.. In my case DOSDP tried to compile against a pattern named $(PATTERNDIR)/.yaml (which of course did not exist).. running strip and removing the double spaces around the strings fixed it; so I assumed that was the problem.. Strange.

**Comment by balhoff** [comment]
Maybe a Makefile issue?

**Comment by matentzn** [comment]
Well, I dont know.

if `--batch-patterns="hello  there     john  "` does not get you an empty string as well as hello, there and john merge it! In any case, ODK knows what to do. If the problem surfaces again we will just submit a ticket.
