### ISSUE TITLE
Feature request: Do not make annotation axiom assertions (such as sbxref on definition assertions) if table cell empty

### ISSUE THREAD

**Issue by matentzn** [INCATools/dosdp-tools#129]
Same as #128 just for annotation assertions.

**Comment by matentzn** [comment]
Another example:

when using 
```
exact_synonym:
   value: exact_syn
```

If the column is present but the cell is empty, currently a relation with an empty string is created, which is undesirable.

**Comment by balhoff** [comment]
Should work now.
