### ISSUE TITLE
Use tsv standard for generate and query commands

### ISSUE THREAD

**Issue by cmungall** [INCATools/dosdp-tools#20]
https://docs.google.com/document/d/1xnmLNRMLO7796VmI4GEVv1jadY3e3srLD3gF03h2GqU/edit?usp=sharing

**Comment by cmungall** [comment]
Example:

https://planteome.github.io/planteome-inca-form

Uses:

https://raw.githubusercontent.com/Planteome/plant-trait-ontology/clean-dp/patterns/composition/composition.tsv

And seems to work.

the GO tsvs look like this:

```
?defined_class  ?defined_class_label    ?regulated_activity     ?regulated_activity_label
```

**Comment by balhoff** [comment]
@cmungall can you spell this out a little more? Is the main problem that the output of query isn't matching the input format? So the var names need to have the '?' removed.

**Comment by balhoff** [comment]
And according to the spec I need to switch back to `|` for delimiter.

**Comment by balhoff** [comment]
I think Planteome should update TSVs to use `defined_class` instead of `iri`.
