### ISSUE TITLE
Feature request: Trim whitespace around cell values in TSV

### ISSUE THREAD

**Issue by matentzn** [INCATools/dosdp-tools#230]
right now, whitepsace in CSV cell values like `label 1 ,test2` (note whitespace after `1`) does not get trimmed. Also, maybe there should be a warning if the DOSDP template accidentally has an erroneous whitespace, like `'% % '` for a label etc..

**Comment by balhoff** [comment]
It seems like this works properly (trimming cell values) but @jdr0887 will implement a couple of tests (both TSV and CSV) to ensure. We can also add the warning for the template.

**Comment by balhoff** [comment]
Fixed by #278.
