### ISSUE TITLE
Consider embedded Blazegraph for pattern queries

### ISSUE THREAD

**Issue by balhoff** [INCATools/dosdp-tools#24]
Pattern queries using Jena (the current SPARQL API) can be quite slow. @cmungall @dougli1sqrd is this becoming too slow for the GO patterns Makefile?

**Comment by cmungall** [comment]
https://build.berkeleybop.org/job/query-go-patterns/buildTimeTrend

Note that the results are cached so it's faster if it doesn't have to recalculate all. Given this it's not imperative to speed this up. But we wouldn't be able to run these as tests in travis at the moment
