### ISSUE TITLE
Coordinate the handling of escape character with DOSDP spec

### ISSUE THREAD

**Issue by matentzn** [INCATools/dosdp-tools#247]
@dosumis @balhoff 

To properly handle single quotes in DOSDP pattern strings (see main [issue](https://github.com/INCATools/dead_simple_owl_design_patterns/issues/55)) we need to be sure this is more or less simultaneously handled in both the spec and the tools.

**Comment by balhoff** [comment]
Decided not to escape; see https://github.com/INCATools/dead_simple_owl_design_patterns/issues/55.
