### ISSUE TITLE
Can I bulk add object properties using dosdp-tools to all classes in an existing ontology?

### ISSUE THREAD

**Issue by msinclair2** [INCATools/dosdp-tools#29]
Hi Jim,

I'd like to know if and how I can use dosdp-tools to add an object property to every class in an ontology.

It's something I know I can do in the OWLAPI, but I'd like to know how to do it in dosdp-tools since it is much less verbose.

The ontology I'm working on, the Sequence Ontology (SO), consists mostly of "generically dependent continuants" that "generically depend on" some independent continuant.  These independent continuants, sequence molecules as physical entities, are the content of an accompanying ontology, the Molecular Sequence Ontology (MSO).

First I will direct import the MSO into a working file of the SO.  I then want to add to every SO class an object property (subclass assertion) of the following format:

genericallyDependsOn some MSOClass

Assuming I have a TSV file which contains in each row an SO class IRI in the first column and the corresponding MSO Class IRI to fill the property in the second column, how would I structure the dosdp template to use with dosdp-tools to accomplish my task?

Thank you!

**Comment by dosumis** [comment]
You could use a pattern + tsv to generate a file of (SO) OWL classes with just a single SubClassOf axiom.  You could then merge this into SO using robot https://github.com/ontodev/robot.

```yaml
pattern: mso_in_so

relations:
    'generically depends on': 'RO:...'

vars: 
    mol: 'owl:Thing'

subclassof: 
    text: "'generically depends on' some %s"
    vars: 
       - mol
```

**Comment by balhoff** [comment]
I agree with @dosumis. The only thing I would add is that you just need to provide appropriate column headers in your TSV (the spec may not be well documented yet). If there is a variable `mol`, you need  column `mol`. And then for the SO class column, use the header `defined_class`.

**Comment by msinclair2** [comment]
Thank you both very much, I will try this.
What is the obo-prefixes option for?  Do I need this or some other prefixes
file in order to specify the full IRI short of the ID number at the end?

**Comment by balhoff** [comment]
If you use `--obo-prefixes`, it will predefine prefix expansions for `rdf`, `rdfs`, and `owl`, and all others will be expanded according to OBO convention. E.g. `GO:` would become `http://purl.obolibrary.org/obo/GO_`. This way you don't have to provide a mapping for each OBO ontology. You can provide a separate mapping file as well and it will override the automatic mappings.

**Comment by msinclair2** [comment]
Thank you Jim.  One last question so I can understand what's going on under
the hood.  Is dosdp-tools set to perform all direct imports and plugin
imports (e.g. MIREOT, Ontofox, Ontorat, etc.) before executing the
command?  All of my MSO is via a direct import statement and not merged and
copied into the SO owl file itself.  So that import will need to be
resolved first before dosdp-tools can recognize IRIs that come from the
MSO.  Will that work?

**Comment by balhoff** [comment]
It will try to load the imports automatically. However, for what your'e doing I don't think you even need to provide an ontology. Since you're just making axioms and not generating annotations, it just needs the term IDs from your TSV. It will output an ontology in OWL Functional syntax.

**Comment by msinclair2** [comment]
So I don't need to preserve the original SO taxonony in the ontology that
gets generated from the TSV?  It will just be a bunch of classes that each
have one Subclass axiom, an existential "generically depends on" assertion,
with no other structure.  I can then use ROBOT to merge these axioms into
the original SO (with MSO directly imported) so that they just get added on
a class by class basis to what's already there?

**Comment by balhoff** [comment]
> So I don't need to preserve the original SO taxonony in the ontology that
gets generated from the TSV?

Right, this will just get merged with what dosdp-tools produces when you merge the ontologies. If you want to continue managing these axioms separately, you can just add an import to the generated ontology and update the imported file whenever you want.

**Comment by msinclair2** [comment]
It's not working.  The ontology file that is generated is completely blank.

David's syntax above wasn't exactly the same as Jim's example file (abnormalSize.yaml) so I altered it to match, but it's still blank.

Another issue I had was that the fields requiring filenames (infile, outfile, etc.) would not allow me to use any kind of relative path to go into other folders; I got the "FileNotFound" exception.  All files had to be exactly in the same directory.

I'm attaching the files I used. Note that because Git does not support custom file extensions, I have to change all extensions to .txt.  Please change them back if necessary to .yaml and .tsv before using.  

The command I used was:

`dosdp-tools generate --obo-prefixes=true --template=SO_depends_on_MSO.yaml --infile=mso_in_so.tsv --outfile=SO_depends_on_MSO.owl`

Thank you in advance for help in troubleshooting this.

[mso_in_so.txt](https://github.com/INCATools/dosdp-tools/files/1357323/mso_in_so.txt)
[SO_depends_on_MSO.txt](https://github.com/INCATools/dosdp-tools/files/1357322/SO_depends_on_MSO.txt)

**Comment by balhoff** [comment]
Update your YAML to match this and it should work:

```yaml
pattern: SO_depends_on_MSO

classes:
    Thing: owl:Thing

relations:
    generically_depends_on:  SO:6000000

vars:
    molecule:  "'Thing'"

subClassOf:
    text:  "'generically_depends_on' some %s"
    vars:
        - molecule
```

The problem was the key `subclassof` instead of `subClassOf`. David had made a typo in his comment (I fixed it). The tool is currently very poor about reporting these kinds of errors because all the keys in the format are optional. And it doesn't care if you have extra keys—I should at least make it report that. I also added a declaration for the "Thing" class, but it doesn't matter in this case.

**Comment by balhoff** [comment]
BTW thanks for all the questions. It helps to have someone try things out from scratch.

**Comment by msinclair2** [comment]
Thanks, that works!  The SO is undergoing some major refactoring now, and
we are hopeful that we can manage it using dosdps.

**Comment by msinclair2** [comment]
This may not be the best place to ask the next question, but one thing I'm
seeing when I just do a direct import of the resulting owl file into my
original ontology, is that under anonymous subclasses, protege is listing
literally every single ancestor of the MSO class that an SO class
generically depends on.

For example if MSO_Z is a subclass of MSO_Y, which is a subclass of MSO_X
at the top, protege lists under anonymous subclasses for class SO_X which
generically depends on MSO_X:

SO_X generically_depends_on MSO_X
SO_X generically_depends_on MSO_Y
SO_X generically_depends_on MSO_Z

Is this a quirk of the output file? Of Protege? Would ROBOT act differently?

**Comment by msinclair2** [comment]
Sorry, I didn't report that quite right.

Under the anonymous subclasses for SO_X, it lists:

generically_depends_on some MSO_X
generically_depends_on some MSO_Y
generically_depends_on some MSO_Z

Here's a screenshot example for the class 'gene':

![2017-10-04-171155_1920x925_scrot](https://user-images.githubusercontent.com/20292982/31204118-799faf1e-a927-11e7-9cda-6e79f21c5f3b.png)

This is rather odd behavior and doesn't happen, for example, if I were to enter the property manually.  If you think it has nothing to do with the owl file output by dosdp-tools, I will ask elsewhere.

**Comment by msinclair2** [comment]
Thanks for all your help by the way, it's hard to be profuse enough in expressing my gratitude.

**Comment by msinclair2** [comment]
I need to issue yet another correction as I still didn't give a correct general example, sigh, although the screenshot is accurate.

Let me try one more time:

"For example if MSO_Z is a subclass of MSO_Y, which is a subclass of MSO_X
at the top, protege lists under anonymous subclasses for class SO_Z which
generically depends on MSO_Z:

SO_X generically_depends_on MSO_X
SO_X generically_depends_on MSO_Y"

In the screen shot, gene (SO) generically depends on gene (MSO), and this is listed in the SubClassOf assertions, which is what dosdp-tools added.  But then in the SubClassOf (anonymous ancestor) I also see generically_depends_on all the ancestors of gene (MSO), 3 of them in fact.

**Comment by msinclair2** [comment]
Please refer to the most recent reply and look at it on the github site rather than email because I made edits after posting.  I badly butchered the explanation of this issue the first few times around :(.

**Comment by balhoff** [comment]
I think this is just a feature of Protege. I did some experiments in Protege and I believe it just shows all expressions found in superclasses of a given term.

**Comment by msinclair2** [comment]
Thank you Jim.  I figured it would be something to ask not here but on the
protege list.  It doesn't do that when such axioms are entered manually,
only on import.  It's messy.  I'll ask them.  Maybe if I do a full merge
with ROBOT before opening in protege it won't happen.

**Comment by msinclair2** [comment]
May I ask, for the generate command, what would be the use case where you would provide a value for the --ontology argument?  It seems like the generate command does not ever merge its results with the provided ontology, it generates a stand-alone owl file every time.  So, what is the purpose of providing an --ontology?

**Comment by dosumis** [comment]
I believe that ontology spec with generate command can be used to check validity of referenced entities.

Re: anonymous axioms: I think you should focus on the logical meaning.    It is correct that subclass of restrictions axioms apply to descendents and it is useful to be able to track this. The pattern you've applied likely makes this information a bit overwhelming, but perhaps you need to think about what you're trying to achieve. Happy to discuss further, but this should be on a SO/MSO repo ticket, not here.

**Comment by balhoff** [comment]
When you pass an ontology to the `generate` command, it can be used to find text labels to be used in generating templated labels and definitions in the new terms.

**Comment by balhoff** [comment]
Since you've got things working, I'll close this ticket. Feel free to open another for further issues.
