### ISSUE TITLE
When a tsv or yaml is not found, dont print stack trace

### ISSUE THREAD

**Issue by matentzn** [INCATools/dosdp-tools#299]
When the tsv or yaml does not exist, currently the full stack trace is printed, and inexperienced users get scared away. Can we not print the stack trace and just say "file X not found"? :)

**Comment by balhoff** [comment]
@jdr0887 I've been trying to put better descriptions of errors inside a `DOSDPError`. Can you get familiar with how ZIO deals with errors at the end of the run method, and if the error is a DOSDPError, print only the message? Or maybe just do that for all errors and add the stack trace if some kind of arg is passed like `-v`.

**Comment by matentzn** [comment]
Similar to something like this:
https://github.com/EnvironmentOntology/environmental-exposure-ontology/runs/3792054352?check_suite_focus=true

**Comment by balhoff** [comment]
Fixed by #300.
