### ISSUE TITLE
Logical axiom IRI resolution issue

### ISSUE THREAD

**Issue by hkir-dev** [INCATools/dosdp-tools#311]
We are using odk v1.2.26

Please see [src.zip](https://github.com/INCATools/dosdp-tools/files/6164442/src.zip) for the complete case.

For given logical_axiom:

>   axiom_type: subClassOf
     text: "%s"
     vars:
       - gross_cell_type

Dosdp cannot resolve 'gross_cell_type' and default text value is used instead of the IRI. Accordingly given error is raised:

> org.semanticweb.owlapi.manchestersyntax.renderer.ParserException: Encountered 'cell' at line 1 column 1. Expected one of:
        Class name
        Object property name
        Data property name
        inverse
        not
        (
        {

For the other patterns (such as "name"), gross_cell_type curie resolved as expected.

**Comment by balhoff** [comment]
Hello @hkir-dev, I haven't tried running this yet, but I did see one issue in the pattern. Within `vars` there is `gross_cell_type: "'cell'"`, however `cell` is not defined in `classes`.

Can you see if fixing that clears up your issue, or if not, please post the command you're running. Thanks!

**Comment by balhoff** [comment]
I think we should add some checks for variable declarations; I made this issue long ago: #62.

**Comment by hkir-dev** [comment]
Hi @balhoff , yes this solved the issue. 
Thank you very much.
