### ISSUE TITLE
Conditional filtering in dosdps

### ISSUE THREAD

**Issue by msinclair2** [INCATools/dosdp-tools#32]
Hi Jim (cc @dosumis @mikebada),

I have two related questions, maybe only one of them needs answering:

1. Is it possible to have conditional if-else style logic in a dosdp so dosdp-tools can only select certain classes based on specified variables?  I'd like to know in any case, but probably the better approach is:  

2.  How can I write a pattern that will filter based on the presence or absence of a property, for either generate or query?  For example, how does one query (or generate using an input ontology to filter out entities in the tsv that don't meet the pattern criteria) for the presence of the annotation property owl:deprecated, in order to return a list of all deprecated classes?  How does one do the inverse, select all classes that _don't_ have the deprecation annotation to get a list of all currently valid classes? 

I'm not sure if this question should be here or should be on the actual dosdp repo; if you think it belongs better there I'll move it over.  Thank you again for your help.  We are making good strides towards a fully refactored SO-MSO that will be thanks to dosdp and dosdp-tools.

**Comment by balhoff** [comment]
Hi, I guess this would probably be best as a question at https://github.com/dosumis/dead_simple_owl_design_patterns, but my initial response would be that for (1) I would probably assume there was some filtering step prior to generating your CSV. For (2), currently there's no way to match on annotation properties; the query mode is only looking at exactly matching logical definitions. We may want to extend that to annotation values defined in the template, but I don't think that's it's exactly what you're looking for.

Maybe something to consider is that in many of our ontology release pipelines we use several different operations provided by [ROBOT](https://github.com/ontodev/robot). You can pass a SPARQL query to robot that will pull out of list of terms (possibly filtering on the deprecation annotation), and then use that list as dosdp-tools input. (You would probably need to use some UNIX command to tweak the the column headers).

**Comment by msinclair2** [comment]
Hi Jim,

Thank you for your response. Two more questions:

1) I'm assuming that dosdp-tools can still create annotation properties for
entities using the generate command?  The 2017 paper (Osumi-Sutherland et
al) exemplifies this as a core feature of dosdps (cf. Figs. 1-2). But the
values would need to be stored as columns in the CSV?

2) I guess your answer also means that dosdp-tools cannot extract any
annotation properties from a term in the "defined_class" column of the tsv
for use elsewhere; e.g. in the generate command, copy and paste, or copy,
modify, and paste, the same annotation property and value (e.g. definition)
from a term under "defined_class" to a term being created (from data in
different columns of the same row in the tsv)?

**Comment by balhoff** [comment]
> 1) I'm assuming that dosdp-tools can still create annotation properties for
entities using the generate command?  The 2017 paper (Osumi-Sutherland et
al) exemplifies this as a core feature of dosdps (cf. Figs. 1-2). But the
values would need to be stored as columns in the tsv?

Yes, it can create annotation property values. You can have a column for it, or it can use one of the IRI columns and it will find a label for the IRI in the ontology you provide.

> 2) I guess your answer also means that dosdp-tools cannot extract any
annotation properties from a term in the "defined_class" column of the tsv
for use elsewhere; e.g. in the generate command, copy and paste, or copy,
modify, and paste, the same annotation property and value (e.g. definition)
from a term under "defined_class" to a term being created (from data in
different columns of the same row in the tsv)?

If I understand correctly, I don't think DOS-DP could do this.

**Comment by msinclair2** [comment]
Thank you David, I've discovered that over the past few days.  I'm having
success just using the OWL API directly, with the ROBOT core library
integrated in for convenience methods.
