### ISSUE TITLE
Support 0-many var input

### ISSUE THREAD

**Issue by hkir-dev** [INCATools/dosdp-tools#334]
Dosdp schema is [updated](https://github.com/INCATools/dead_simple_owl_design_patterns/issues/71) to support 0-many var inputs. With this schema update given supports are added:

-  Internal vars added to apply basic operations (such as join and regex) on data_list_vars and introduce new variables.
- Multi_clause structure added to support optional clauses
- Utilization of clauses and data_list_vars/list_vars together to support cardinality > 1 cases

Related YAML decoder and OWL generator codes need to be implemented.

**Comment by dosumis** [comment]
This is now partly supported via https://github.com/INCATools/dosdp-tools/pull/336
=> support for multi-clause printf with optionals

@hkir-dev  - one quick question: are optionals only supported inside multi-clause printf statements?

We still need support for list_var -> multiple clauses in the context of multi-clause printf.

**Comment by hkir-dev** [comment]
Yes, optionals only work within multi-clause printf statements.

**Comment by dosumis** [comment]
Would be good to boost priority of this work.  It will help simplify the BDS ontology build enormously.

**Comment by dosumis** [comment]
Fixed bu #349
