### ISSUE TITLE
New command: Generate markdown docs

### ISSUE THREAD

**Issue by cmungall** [INCATools/dosdp-tools#34]
DPs are vital not just for automated procedures on an ontology, but also for documentation too. It's important for documentation to be easily browsed and to look intuitive to semi-technical readers.

@dosumis already implemented a dosdp->md translation in jython, predating dosdp-tools:

https://github.com/dosumis/dead_simple_owl_design_patterns/blob/master/src/attic/pattern.py#L207

example: https://github.com/dosumis/dead_simple_owl_design_patterns/blob/master/patterns/integral_membrane_component.md

Having this reimplemented in scala would make it easier to have everything working as one package, but if this is a lot of work may be better to reuse? 

Some things that would also be nice to have:

 * ability to embed markdown directly within the yaml doc for enhanced human-friendly docs (we could invert this and use yamldown, see the obo md files for examples, but this would probably be too much churn)
 * ability to include examples (and counterexamples?) within a DP. This would also be good for unit tests
 * linking to PURLs for all declared classes and relations
 * self-reporting the PURL for the pattern itself (e.g. `$OBO/$ONTID/patterns/$NAME`)
 * links to subsuming or subsumed patterns, or patterns that use the same vars

## documentation servers

Although probably out of scope for dosdp-tools, but providing for context:

although github can render markdown docs just fine, it would be nice to have the html more directly. We could have a documentation server, but it may be better to go a static site route.

many ontologies like uberon have static sites built using Jekyll (GO may go this way). obofoundry.org also uses this. Markdown is rendered by default. It should be relatively easy to write liquid templates that would list all DPs for an ontology. For example [this list](http://uberon.github.io/downloads.html#bridge) is made automatically for a yaml config.

This may still be a lot of work for some ontologies that do not have static sites. They should have the option of generating markdown and depositing it in github and linking directly to this (one awkwardness is that PURLs for the patterns will not have the .md suffix). This is fine, but we may also want to consider registering patterns with OBO central (in the usual way, adding to the md file for each ontology) and having the OBO central jekyll framework render all known patterns (cc @jamesaoverton)

**Comment by matentzn** [comment]
+1 for a nice way to browse patterns and show better documentation on Github pages. I think this reimplementation has to be lead by @balhoff, not sure what I can do to help. 

This idea with an OBO-registry for pattern: would it be a page similar to the ontologies page, showing domains, metadata (names etc)? That would be kind of cool - especially since the search for appropriate patterns becomes increasingly difficult.
