### ISSUE TITLE
Add support for generated synonym fields

### ISSUE THREAD

**Issue by dosumis** [INCATools/dosdp-tools#40]
[These fields](https://github.com/dosumis/dead_simple_owl_design_patterns/blob/master/spec/DOSDP_schema_full.yaml#L337) have been in for some time, but appear to be ignored by dosdp_tools

e.g. [this pattern](https://github.com/FlyBase/drosophila-anatomy-developmental-ontology/blob/49ea8201daeb11f9f708ec6fbbedd6879e0528c9/fbbt/src/patterns/VNC_subdomain.yml) passes local schema tests but silently fails to generate synonyms

Please could you add support?

**Comment by balhoff** [comment]
I'm confused: the current implementation supports the same functionality but as:

```json
exact_synonym:
    $ref: '#/definitions/printf_annotation_obo'
    mapping: "oboInOwl:hasExactSynonym"
  narrow_synonym:
    $ref: '#/definitions/printf_annotation_obo'
    mapping: "oboInOwl:hasNarrowSynonym"
```

Were these swapped around at some point with `generated_synonyms`? It seems like this will break existing patterns.

**Comment by dosumis** [comment]
> I'm confused

Sorry.  Probably my fault for lack of clear doc.

Two different use cases

This are list annotations. 

```yaml
  exact_synonym:
    $ref: '#/definitions/list_annotation_obo'
    mapping: "oboInOwl:hasExactSynonym"
  narrow_synonym:
    $ref: '#/definitions/list_annotation_obo'
    mapping: "oboInOwl:hasNarrowSynonym"
```
'var' has value list of strings.  Each one is used to create an AP axiom.


-----

These fields allow synonyms to be generated from interpolation into text as for other printf_annotation fields. 

```yaml
  generated_synonyms:
    description: >
      An OBO convenience field to allow the specification of exact synonyms
      generated by interpolation of OWL entity names into printf text.
      Each entry may be annotated. 
    type: array
    items:  
      $ref: '#/definitions/printf_annotation_obo' 
      mapping: "oboInOwl:hasExactSynonym"
```

(see example linked above).

This is an obo convenience field.  The same result can be achieved by adding entries under "annotations" but requires knowing the correct AP to specify.  I guess it's a marginal call whether this adds unnecessary complexity.  I'll add using the generic pattern for now.

**Comment by dosumis** [comment]
Actually - think it is worth having these convenience fields, as otherwise need additional prefixes file for oboInOwl APs

**Comment by dosumis** [comment]
Hmmm - still not working.

I have a prefixes.yml with: 

```yaml
oboInOwl: "http://www.geneontology.org/formats/oboInOwl#"
```

And a pattern with:

```yaml
annotations:
    - 
        annotationProperty: "oboInOwl:hasExactSynonym"
        text: "%s neuropil of %s"
        vars:
            - long_sub
            - segment
    -
        annotationProperty: "oboInOwl:hasExactSynonym"
        text: "%s%s"
        vars:
            - seg_abbv
            - sub_abbv
```

But running this:

 /repos/dosdp-tools-0.6.1/bin/dosdp-tools --prefixes=prefixes.yml --ontology=../ontologies/fbbt-edit.obo --template=VNC_subdomain.yml --outfile=VNC_subdomains.obo generate --infile=VNC_subdomain.tsv

Still gives me:

2018-02-17 07:10:34,347 ERROR org.monarchinitiative.dosdp.ExpandedDOSDP - No annotation property binding: oboInOwl:hasExactSynonym

Despite this being present in the OWL (under standard OWL-API OBO to OWL translation)

![image](https://user-images.githubusercontent.com/112839/36339064-111a4a28-13b5-11e8-96e3-0c5bcb77cdd0.png)

**Comment by balhoff** [comment]
Try adding a field to your file:

```yaml
annotationProperties:
    hasExactSynonym: 'oboInOwl:hasExactSynonym'
```

And then use hasExactSynonym everywhere else. That brings up a question about how things should work. Should folks be able to use IRIs or CURIEs anywhere they want, rendering term declarations optional?

**Comment by dosumis** [comment]
Doh.  Forgetting my own spec...  Now works.

> Should folks be able to use IRIs or CURIEs anywhere they want, rendering term declarations optional?

Probably not as would get in the way of pattern readability for all cases without readable short_forms.

Would be nice to have the generated synonym fields working at some point, but no rush.  Thanks.

**Comment by marieALaporte** [comment]
I am also trying to create a synonym field.
This is the code I use:

> exact_synonym: 
  text: "%s"
  vars:
    - synonym

But I am getting a key not found error. If I understand correctly from the conversation, I cannot just yet add a simple string synonym using dosdp-tools?
I was using generated_synonyms before. No errors, but nothing happening. This is why I switched to the exact_synonym solution.

**Comment by balhoff** [comment]
@marieALaporte are you using `data_vars`? If not that may work. I am just starting to test this to make sure it works as expected in dosdp-tools.
