### ISSUE TITLE
When generating definitions/syns, and multiple labels are present, dosdp tools create weird values.

### ISSUE THREAD

**Issue by matentzn** [INCATools/dosdp-tools#412]
When the source ontology, say foodon, contains terms with more than one label (shrimp, "shrimp as a food source"), dosdp tools generate bad looking definitions:

```
An exposure to shrimp as food sourceshrimp via ingestion.
```

and synonyms:

```
shrimp as food sourceshrimp exposure via ingestion
```

**Comment by matentzn** [comment]
See also 

- https://github.com/enpadasi/Ontology-for-Nutritional-Studies/issues/34
- https://github.com/EnvironmentOntology/environmental-exposure-ontology/pull/227

**Comment by matentzn** [comment]
Also, if there are multiple labels, the choice of which label to use should be deterministic. Not sure this is the case.

**Comment by balhoff** [comment]
@matentzn is this in `generate`?
