### ISSUE TITLE
use defined_class label if it exists

### ISSUE THREAD

**Issue by marieALaporte** [INCATools/dosdp-tools#42]
Would it be possible that dosdp-tools does not overwrite the defined class label if the defined_class label is not empty in the tsv file.
The label could be created using the yaml file only if that colum is empty

**Comment by balhoff** [comment]
I think this is a good idea. But we want to make sure we don't have too much magic that is not in the spec. We could have that if there is a value in column `defined_class_label`, it overrides the result of the `name` template (especially since that is OBO-specific). Other mechanisms that assert `rdfs:label` annotations wouldn't be affected (like using `annotations` directly).

@dosumis this could potentially work as an OBO special case of a general override mechanism for any `printf_annotation_obo`. Maybe we could have a field to specify a variable name that may or may not be empty in the TSV.

**Comment by dosumis** [comment]
Agree general override mechanism desirable for printf_annotation fields.  We discussed this for obo name and def fields last year at the GO meeting in Corvallis and all agreed it was needed.

@balhoff - maybe we should do this using a naming convention for over-ride columns.  Does that seem reasonable?

It's also way past time to get a formal spec of the tsv out.  I had a go at this last year using a W3C standard for csv spec but I think the draft is still stuck on a ticket.    I'll dig this out and post soon as part of general cleanup/doc of DOSDP.

**Comment by balhoff** [comment]
How about this extension to `printf_annotation` (see `override` at end):

```yaml
printf_annotation:
    type: object
    additionalProperties: False
    required: [annotationProperty, text]
    properties:
      annotationProperty:
        description: > 
         A string corresponding to the rdfs:label
         of an owl annotation property. If the annotation property has no label,
         the shortForm ID should be used. The annotation property must be listed
         in the annotation property dictionary.'
        type: string
      annotations:
        items: { $ref: "#/definitions/annotations" } 
        type: array
      text:
        description: A print format string.
        type: string
      vars:
        description: >
         An ordered list of variables for substitution into the accompanying
         print format string. Each entry must correspond to the name of a variable
         specified in either the 'vars' field or the data_var field of the pattern.
         Where an OWL entity is specified, the label for the OWL entity should be
         used in the substitution.  An empty var list can be specified simply by
         leaving this field out.
        items: {type: string}
        type: array
      override:
        description: >
          An input column name which, if not empty, directly provides a value for this 
          annotation, overriding the computed value.
        type: string
```

Then for OBO fields there can be some built-in overrides. For example, `name` automatically uses an `override` value of `defined_class_label`.

**Comment by balhoff** [comment]
And the same for `list_annotation`.

**Comment by matentzn** [comment]
This feature is also very important to me. :) Let me know if there is anything I can do to help! @balhoff do you have a timeline for this?
