### ISSUE TITLE
dosdp query does not work with 'Thing'

### ISSUE THREAD

**Issue by marieALaporte** [INCATools/dosdp-tools#43]
dosdp-tools generate works with this [pattern](https://github.com/austinmeier/ontology-of-plant-stress/blob/master/src/ontology/patterns/disease.yaml) but dosdp-tools query does not because of the use of "Thing" in the variable part.

The error  I got:
`Exception in thread "main" org.semanticweb.owlapi.manchestersyntax.renderer.ParserException: Encountered Thing at line 1 column 1.
`

**Comment by balhoff** [comment]
`generate` doesn't look at that field, so it doesn't cause an error. Add Thing to your classes list with value `owl:Thing`, and either define the prefix or use `--obo-prefixes`.

**Comment by marieALaporte** [comment]
Thanks it worked.
I was thinking that the generate command was checking that the yaml file was complete.
