### ISSUE TITLE
annotate generated axioms to specify pattern

### ISSUE THREAD

**Issue by balhoff** [INCATools/dosdp-tools#46]
Axioms generated by dosdp-tools should be annotated to point to the pattern used. Perhaps some PURL made from ontology PURL: `$OBO/$ONT/patterns/abnormal_phenotype.yaml` ?

**Comment by balhoff** [comment]
Should a DOS-DP pattern include an IRI field within the pattern?

**Comment by matentzn** [comment]
There is no perfect one like hasSourcePattern; but since this is likely the only annotation the equivalenceclasses axiom will have, what about 

http://purl.org/dc/elements/1.1/source

I would reaaaaally love this feature :P

**Comment by matentzn** [comment]
Chris says: obo in owl source better to ensure OBO-OWL roundtrip
