### ISSUE TITLE
Add are more meaningful message when TSV does not contain correctly named column

### ISSUE THREAD

**Issue by matentzn** [INCATools/dosdp-tools#64]
Currently, if a dosdp cannot find a column in the tsv that it expects from the pattern definition, it says:

```
key not found: biological_process
Exception in thread "main" java.util.NoSuchElementException: key not found: biological_process
```
To be more user friendly, maybe instead just say:
```
TSV file does not contain the required column biological_process
```

**Comment by balhoff** [comment]
Columns will now be optional according to #185. I should add some warning output when the TSV is read if there are missing columns.

**Comment by matentzn** [comment]
I am slightly worried to make the columns in the vars: section of the dosdp template optional by default; Maybe I am too close to the EQ use case, but dropping the EQ because a column is misnamed that contains a filler variable seems risky. But maybe I am wrong! Would it be easy to create a switch to allow the central variables (those in the `vars:` section, not data_vars, or data_list_vars) to be required (or better have them required by default and only skip the requirement with that switch parameter)? Or else, make a nice and visible warning whenever a template column is not found in a TSV? What do you think @dosumis

**Comment by balhoff** [comment]
I've implemented "a nice and visible warning" in a PR. It seems like this will help avoid unexpected missing output.
